name: Dev Container Build and Push Image

on:
  push:
    tags:
      - "devcontainer/v*.*.*"

jobs:
  devcontainer-build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Compute metadata
        id: meta
        run: |
          tag="${GITHUB_REF#refs/tags/devcontainer/v}"
          repo_lower=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "tag=$tag" >> "$GITHUB_OUTPUT"
          echo "repo_lower=$repo_lower" >> "$GITHUB_OUTPUT"
          echo "image_name=ghcr.io/$repo_lower/devcontainer" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and release devcontainer
        run: |
          npm install -g @devcontainers/cli
          devcontainer build \
            --workspace-folder .github \
            --image-name ${{ steps.meta.outputs.image_name }}:${{ steps.meta.outputs.tag }} \
            --image-name ${{ steps.meta.outputs.image_name }}:latest \
            --platform linux/amd64 \
            --push
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: true
